var assert = require('assert');
var daySix = require("../lib/daySix.js");



describe('daySix', function () {

    describe('daySix.parseArray - given an array of x, y coordinates  ', function () {
        it('should return an object with the minimum and maximum x and y coordinates', function (){
            var coordArray = ["1, 1", 
                              "1, 6",
                              "8, 3",
                              "3, 4",
                              "5, 5",
                              "8, 9"
                          ];
                       
            var expectedXYArray = [{xCoord: 1, yCoord: 1},
                            {xCoord: 1, yCoord: 6},
                            {xCoord: 8, yCoord: 3},
                            {xCoord: 3, yCoord: 4},
                            {xCoord: 5, yCoord: 5},
                            {xCoord: 8, yCoord: 9}
                           ];
            var xyArray = daySix.parseArray(coordArray);

            assert.deepEqual(xyArray, expectedXYArray);
                              
        });

    });

    describe('daySix.findMinMax - given an array of x, y objects  ', function () {
        it('should return an object with the minimum and maximum x and y coordinates', function (){
            var xyArray = [{xCoord: 1, yCoord: 1},
                           {xCoord: 1, yCoord: 6},
                           {xCoord: 8, yCoord: 3},
                           {xCoord: 3, yCoord: 4},
                           {xCoord: 5, yCoord: 5},
                           {xCoord: 8, yCoord: 9}
                          ];
                       
            var expectedObject = {xMin: 1,
                                  xMax: 8,
                                  yMin: 1,
                                  yMax: 9}
            var minMaxObject = daySix.findMinMax(xyArray);

            assert.deepEqual(minMaxObject, expectedObject);
                              
        });

    });

    describe('daySix.createGrid - given an min and max value for x and y  ', function () {
        it('should return an array of initialized objects', function (){
                   
            var minMaxObject = {xMin: 1,
                                xMax: 8,
                                yMin: 1,
                                yMax: 9};
            var targetCoordinateGird = daySix.createGrid(minMaxObject);
            var expectedCoordinateGrid = [[{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],

                    [{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],

                    [{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],

                    [{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],
      
                    [{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],  
                
                    [{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],

                    [{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],

                    [{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],

                    [{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],

                    [{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],

                    [{closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30},
                    {closestTargetX: -1, closestTargetY: -1, manhattenDistanceToClosest: 30}],
                
                ];

            assert.deepEqual(targetCoordinateGird, expectedCoordinateGrid);
                              
        });

    });
    describe('daySix.calculateManhattenDistances - given an array of coordinates  ', function () {
        it('should return a grid with the shortest manhatten distance filled in for all coordinates', function (){
            var coordArray = ["1, 1", 
            "1, 6",
            "8, 3",
            "3, 4",
            "5, 5",
            "8, 9"
        ];

            var expectedCoordinateGrid = [ [ { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 5 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 4 } ],
            [ { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 3 } ],
            [ { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 } ],
            [ { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 1 } ],
            [ { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 3 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 3 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 1 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 5 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 5 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 5 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 } ] ];

            var coordinateGrid = daySix.calculateManhattenDistances(coordArray);

            assert.deepEqual(coordinateGrid, expectedCoordinateGrid);
                              
        });
    });
    describe('daySix.eliminateInfinites - given an array of manhatten distances anda minMaxObject  ', function () {
        it('should return an array of coordinate objects that are not infinite', function (){
            var coordinateGrid = [ [ { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 5 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 4 } ],
            [ { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 3 } ],
            [ { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 } ],
            [ { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 1,
                closestTargetY: 1,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 1 } ],
            [ { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 3,
                closestTargetY: 4,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 3,
                manhattenDistanceToClosest: 3 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 3 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 5,
                closestTargetY: 5,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 0 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 1 } ],
            [ { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 5 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 1,
                closestTargetY: 6,
                manhattenDistanceToClosest: 5 },
              { closestTargetX: -1,
                closestTargetY: -1,
                manhattenDistanceToClosest: -1 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 5 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 4 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 3 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 1 },
              { closestTargetX: 8,
                closestTargetY: 9,
                manhattenDistanceToClosest: 2 } ] ];

 
             
            var xyArray = [{xCoord: 1, yCoord: 1},
                {xCoord: 1, yCoord: 6},
                {xCoord: 8, yCoord: 3},
                {xCoord: 3, yCoord: 4},
                {xCoord: 5, yCoord: 5},
                {xCoord: 8, yCoord: 9}
               ];

            var expectedXYArray =  [{xCoord: 3, yCoord: 4},
                                    {xCoord: 5, yCoord: 5}
            ];

            
            
            daySix.eliminateInfinites(coordinateGrid, xyArray);
            

            assert.deepEqual(xyArray, expectedXYArray);
                              
        });

    });
    describe('daySix.mostElements - given an array of x, y coordinates  ', function () {
      it('should return the number of closest elements for the coordinates that have the most elements but is notinfinite ', function (){
          var coordArray = ["1, 1", 
                            "1, 6",
                            "8, 3",
                            "3, 4",
                            "5, 5",
                            "8, 9"
                        ];
                     
          var expectedNumberOfElements = 17;
          var numberOfElements = daySix.mostElements(coordArray);

          assert.equal(numberOfElements, expectedNumberOfElements);
                            
      });

  });
  describe('daySix.sumManhattenDistances - given an array of x, y coordinates and the coordinates for a single elementon a grid ', function () {
    it('should return the sum of the manhatten distances from the element to each of the coordinates ', function (){
        var coordArray = ["1, 1", 
                          "1, 6",
                          "8, 3",
                          "3, 4",
                          "5, 5",
                          "8, 9"
                      ];
                   
        var expectedSumOfManhattenDistance = 30;
        var sumOfManhattenDistance = daySix.sumManhattenDistances(coordArray, 4, 3);

        assert.equal(sumOfManhattenDistance, expectedSumOfManhattenDistance);
                          
    });

  });

  describe('daySix.findCloseElements - given an array of x, y coordinates and a limit  ', function () {
    it('should return a count of the elements whose manhatten distance sum is within the given limit', function (){
        var coordArray = ["1, 1", 
                          "1, 6",
                          "8, 3",
                          "3, 4",
                          "5, 5",
                          "8, 9"
                      ];

        var sumLimit = 32;              
                   
        var expectedCloseElements = 16;
        var closeElements = daySix.findCloseElements(coordArray, sumLimit);

        assert.equal(closeElements, expectedCloseElements);
                          
    });

  });
});